export var ToanWeapons = [
  {
    id: 1,
    name: 'Dagger',
    description: 'Fairly easy to use. Default weapon.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/1.png'),
  },
  {
    id: 2,
    name: 'Baselard',
    description: 'A big single-edged sword with long reach. Easy to use.',
    user: 'Toan',
    upgrade: [13, 10],
    stage: 1,
    abillity: null,
    image: require('./img/2.png'),
  },
  {
    id: 3,
    name: 'Crysknife',
    description: 'Stylet with magical power.',
    user: 'Toan',
    upgrade: [12, 9],
    stage: 1,
    abillity: null,
    image: require('./img/3.png'),
  },
  {
    id: 4,
    name: 'Gladius',
    description: 'Light wt. double-edged sword. Fairly high attack power.',
    user: 'Toan',
    upgrade: [8, 12],
    stage: 1,
    abillity: null,
    image: require('./img/4.png'),
  },
  {
    id: 5,
    name: 'Kitchen Knife',
    description: 'Low attack power but causes major damage to water monsters.',
    user: 'Toan',
    upgrade: [10, 8],
    stage: 1,
    abillity: 10,
    image: require('./img/5.png'),
  },
  {
    id: 6,
    name: 'Bone Rapier',
    description: 'Made of bone. Ability unknown.',
    user: 'Toan',
    upgrade: [18],
    stage: 1,
    abillity: null,
    image: require('./img/6.png'),
  },
  {
    id: 7,
    name: 'Buster Sword',
    description: 'Double-edged powerful sword.',
    user: 'Toan',
    upgrade: [16],
    stage: 1,
    abillity: null,
    image: require('./img/7.png'),
  },
  {
    id: 8,
    name: 'Chopper',
    description: 'Light and easy to use dagger.',
    user: 'Toan',
    upgrade: [17, 15],
    stage: 1,
    abillity: null,
    image: require('./img/8.png'),
  },
  {
    id: 9,
    name: 'Sand Breaker',
    description: 'Made of desert sand. Absorbs water.',
    user: 'Toan',
    upgrade: [14],
    stage: 1,
    abillity: 13,
    image: require('./img/9.png'),
  },
  {
    id: 10,
    name: 'Sax',
    description: 'Easy to use single-handed sword.',
    user: 'Toan',
    upgrade: [17],
    stage: 1,
    abillity: null,
    image: require('./img/10.png'),
  },
  {
    id: 11,
    name: 'Serpent Sword',
    description: 'Sword with absolute power over snakes. Extremely rare.',
    user: 'Toan',
    upgrade: [20, 18],
    stage: 1,
    abillity: null,
    image: require('./img/11.png'),
  },
  {
    id: 12,
    name: 'Small Sword',
    description: 'Light and easy to use sword.',
    user: 'Toan',
    upgrade: [20],
    stage: 1,
    abillity: null,
    image: require('./img/12.png'),
  },
  {
    id: 13,
    name: 'Shamshir',
    description: 'Characterized by its curved edge. Light and easy to use.',
    user: 'Toan',
    upgrade: [17],
    stage: 1,
    abillity: null,
    image: require('./img/13.png'),
  },
  {
    id: 14,
    name: 'Antique Sword',
    description: 'Sword of antiquity made a long time ago.',
    user: 'Toan',
    upgrade: [24],
    stage: 1,
    abillity: 12,
    image: require('./img/14.png'),
  },
  {
    id: 15,
    name: 'Choora',
    description: 'A dagger with pretty pattern on it.',
    user: 'Toan',
    upgrade: [29],
    stage: 1,
    abillity: null,
    image: require('./img/15.png'),
  },
  {
    id: 16,
    name: 'Claymore',
    description: 'Big and double-handed. Heavy and powerful.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/16.png'),
  },
  {
    id: 17,
    name: 'Dusack',
    description: 'Unique single-hand sword. Cuts well.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/17.png'),
  },
  {
    id: 18,
    name: 'Evilcise',
    description: 'Single-edged sword with magical power.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/18.png'),
  },
  {
    id: 19,
    name: 'Macho Sword',
    description: 'Sword with muscle power. Arming it makes you exercise.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/19.png'),
  },
  {
    id: 20,
    name: 'Tsukikage',
    description: 'Sword with sacred power of moon beam.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/20.png'),
  },
  {
    id: 21,
    name: 'Wise Owl Sword',
    description: "Legendary sword made by Wise Owl's artisan.",
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/21.png'),
  },
  {
    id: 22,
    name: '7 Branch Sword',
    description: 'Ancient sword with mysterious power.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/22.png'),
  },
  {
    id: 23,
    name: "Aga's Sword",
    description: 'Sword owned by legendary hero Aga.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/23.png'),
  },
  {
    id: 24,
    name: 'Brave Ark',
    description: 'Legendary treasure that was revived after many years.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/24.png'),
  },
  {
    id: 25,
    name: 'Cross Hinder',
    description: 'Very powerful double hand treasure sword.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/25.png'),
  },
  {
    id: 26,
    name: 'Drain Seeker',
    description: 'Feared magic sword. Absorb health power.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: 4,
    image: require('./img/26.png'),
  },
  {
    id: 27,
    name: "Heaven's Cloud",
    description: 'Belongs to Katanas. Has the strongest potential.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/27.png'),
  },
  {
    id: 28,
    name: "Lamb's Sword",
    description: 'Timid. Sword like a lamb. Appears to be weak but...',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/28.png'),
  },
  {
    id: 29,
    name: 'Maneater',
    description: 'Fearful sword that eats human souls.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/29.png'),
  },
  {
    id: 30,
    name: 'Mardan Eins',
    description: 'Sword dwelled in by Lucky Mardan Garayan.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/30.png'),
  },
  {
    id: 31,
    name: 'Sun Sword',
    description: 'Legendary sword with power to cut through darkness.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/31.png'),
  },
  {
    id: 32,
    name: 'Atlamillia Sword',
    description: 'Sword that inherited Atlamilla, the legendary gem.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/32.png'),
  },
  {
    id: 33,
    name: 'Big Bang',
    description: "Star energy is condensed and creates sword's energy.",
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/33.png'),
  },
  {
    id: 34,
    name: 'Dark Cloud',
    description: 'Magical sword with the power of darkness.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/34.png'),
  },
  {
    id: 35,
    name: 'Mardan Twei',
    description: 'Sword dwelled in by Lucky Mardan Garayan.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/35.png'),
  },
  {
    id: 36,
    name: '7th Heaven',
    description: 'Beautiful sword. Tears the heavens.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/36.png'),
  },
  {
    id: 37,
    name: 'Arise Mardan',
    description: 'Sword dwelled in by Lucky Mardan Garayan.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/37.png'),
  },
  {
    id: 38,
    name: 'Chronicle Sword',
    description: 'Worlds crumble before its might.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/38.png'),
  },
  {
    id: 39,
    name: 'Sword of Zeus',
    description: "Zeus' swords with unlimited ability.",
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/39.png'),
  },
  {
    id: 40,
    name: 'Chronicle 2',
    description: 'Proof of subjugation. Demon Shaft.',
    user: 'Toan',
    upgrade: [],
    stage: 1,
    abillity: null,
    image: require('./img/40.png'),
  },
];
